# Generated by Django 5.2 on 2025-04-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("cgpa", models.DecimalField(decimal_places=2, max_digits=3)),
                ("semester_credit_load", models.IntegerField()),
                ("sleep_quality", models.CharField(max_length=10)),
                ("physical_activity", models.CharField(max_length=10)),
                ("diet_quality", models.CharField(max_length=10)),
                ("social_support", models.CharField(max_length=10)),
                ("relationship_status", models.CharField(max_length=10)),
                ("financial_stress", models.IntegerField()),
                (
                    "substance_use",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "counseling_service_use",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "family_history",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "chronic_illness",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "extracurricular_involvement",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "residence_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stress_level", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "depression_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("anxiety_score", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "user_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.userresponse",
                    ),
                ),
            ],
        ),
    ]
