# Generated by Django 5.2 on 2025-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default-avatar.png", upload_to="profile_pics"
            ),
        ),
    ]
